### ISSUE TITLE
Trouble capturing error.

### ISSUE THREAD

**Issue by Taransworld** [greg-kennedy/p5-Net-Discord-Webhook#1]
First, your library is awesome.  Thank you so much!!!

Everything works great however I need to go through a LARGE list of webhooks and I need to know when there is an error sending to a webhook and what it is. Using the eval command I can see when the library errors on a webhook but don't know the reason. 

On the command line it outputs this:
`Warning: HTTP::Tiny->post(https://discordapp.com/api/webhooks/yyyyyyyyyyyyyy/xxxxxxxxxxxxxx) returned: 401 UNAUTHORIZED: '{"message": "Invalid Webhook Token", "code": 50027}' at C:\inetpub\wwwroot\GoW_RSS\test3.pl line 11.
`
But I can't capture it.  :(
 
The closest I can come to knowing if there was an error is this code: 
`use WebService::Discord::Webhook;
$url='https://discordapp.com/api/webhooks/yyyyyyyyyyyyyy/xxxxxxxxxxxxxx';
my $webhook = WebService::Discord::Webhook->new( $url );
eval {
	$webhook->execute( content => 'TEST 333' );
} or do {
	print "\nError sending data to webhook.";
};
print "\ndone...";
`

Thank you very much!!!  :)

**Comment by greg-kennedy** [comment]
Sorry for the delay.  GitHub didn't notify me when this issue was created, or I missed it...

I had originally expected people to catch and handle errors from the library like this:

    eval {
        # try your code which may cause errors
        $webhook->execute("Test message!");
    };
    if ( $@ ) {
        # the error message is in $@, you can do regex on it or something
        print "Looks like there was an error: $@\n";
    }

However, it looks like I'm printing the failures with `warn` rather than `die`, which can't be caught this way!  This is my first module so I'm going to ask on PerlMonks for advice on the best way to handle errors.  Probably, it should just `die` for everything, but I'd like to check options first.

In the meantime, it IS possible to catch the output of `warn` by overriding the signal handler in `%SIG`.  See if this link helps you.  https://perlmaven.com/how-to-capture-and-save-warnings-in-perl

Leaving this open until I have a better solution :)

**Comment by greg-kennedy** [comment]
The newest version of this library now raises an exception (with `croak()`) for every error, instead of a mix of `warn` / `die` / `return undef`.  It should now be possible to capture this using `eval {}` and test the errors using the pattern above.  A brief note on this is in README.pod.
